export enum CategoryDetailsEnum {
    TINH_THANH = "TINH_THANH",
    QUAN_HUYEN = "QUAN_HUYEN",
    PHUONG_XA = "PHUONG_XA",
    LOAI_DAT = "LOAI_DAT",
    BUSINESS_TYPE = "BUSINESS_TYPE",
    BUSINESS_MODEL = "BUSINESS_MODEL",
    SOIL_TYPE = "SOIL_TYPE",
    PRODUCT_TYPE = "PRODUCT_TYPE",
    UNIT_TYPE = "UNIT_TYPE"
}