export enum Service {
    USER_SERVICE = "USER_SERVICE",
    AUTH_SERVICE = "AUTH_SERVICE",
    MANAGER_SERVICE = "MANAGER_SERVICE",
    PERMISSION_SERVICE = "PERMISSION_SERVICE",
    FEATURE_SERVICE = "FEATURE_SERVICE",
    LAND_SERVICE = "LAND_SERVICE",
    FARM_SERVICE = "FARM_SERVICE",
    AREA_SERVICE = "AREA_SERVICE",
    SOIL_TYPE_SERVICE = "SOIL_TYPE_SERVICE",
    IMAGE_SERVICE = "IMAGE_SERVICE",
}